(add-to-list 'load-path (concat user-emacs-directory "elisp"))

(require 'base)
(require 'base-extensions)
(require 'base-functions)
(require 'base-global-keys)
(require 'base-theme)
(require 'lang-cpp)
(require 'lang-org)
(require 'lang-rust)
(require 'lang-typescript)
